kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3-slim-stretch
  commands:
  - pip install -r requirements.txt
  - pytest
- name: run
  image: python:3-slim-stretch
  commands:
    - python app.py
